import type { Project } from "@/types/project";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    title: "Maus Tratos a Animais",
    description:
      "Normalização de laudos veterinários e registros de ocorrência policial.",
    aiContext: "",
    tasks: { normalize: true, classify: false },
    columnsToNormalize: ["acusado", "vítima"],
    columnsToClassify: [],
    normalizations: 2733,
    classifications: 0,
    lastRun: "2026-05-16T10:00:00Z",
    createdAt: "2026-04-01T00:00:00Z",
    uploadedFile: {
      id: "f1",
      name: "dados.csv",
      size: 24000,
      rows: 1200,
      uploadedAt: "2026-05-16T09:00:00Z",
    },
    normalizedFile: {
      id: "n1",
      name: "dados_normalized.csv",
      size: 22000,
      rows: 1200,
      generatedAt: "2026-05-16T10:00:00Z",
      downloadUrl: "/download/n1",
    },
  },
  {
    id: "2",
    title: "Improbidade Administrativa",
    description:
      "Classificação de cargos e normalização de nomes de réus em processos.",
    aiContext: "Focar em cargos públicos municipais e estaduais do Brasil.",
    tasks: { normalize: true, classify: true },
    columnsToNormalize: ["réu", "cargo"],
    columnsToClassify: ["cargo"],
    normalizations: 3491,
    classifications: 1820,
    lastRun: "2026-05-17T14:30:00Z",
    createdAt: "2026-03-15T00:00:00Z",
    uploadedFile: {
      id: "f2",
      name: "improbidade_2024.xlsx",
      size: 81000,
      rows: 4300,
      uploadedAt: "2026-05-17T14:00:00Z",
    },
    normalizedFile: {
      id: "n2",
      name: "improbidade_2024_normalized.csv",
      size: 78000,
      rows: 4300,
      generatedAt: "2026-05-17T14:30:00Z",
      downloadUrl: "/download/n2",
    },
  },
  {
    id: "3",
    title: "Crimes Contra o Patrimônio",
    description: "",
    aiContext: "",
    tasks: { normalize: true, classify: false },
    columnsToNormalize: [],
    columnsToClassify: [],
    normalizations: 1193,
    classifications: 0,
    lastRun: null,
    createdAt: "2026-05-10T00:00:00Z",
    uploadedFile: {
      id: "f3",
      name: "patrimônio_jan_jun.csv",
      size: 12000,
      rows: 640,
      uploadedAt: "2026-05-18T08:00:00Z",
    },
    normalizedFile: null,
  },
  {
    id: "4",
    title: "Violência Doméstica",
    description:
      "Extração e normalização de nomes de vítimas e agressores em boletins de ocorrência.",
    aiContext: "",
    tasks: { normalize: false, classify: false },
    columnsToNormalize: [],
    columnsToClassify: [],
    normalizations: 0,
    classifications: 0,
    lastRun: null,
    createdAt: "2026-05-18T00:00:00Z",
    uploadedFile: null,
    normalizedFile: null,
  },

  /* ── Em processamento ─────────────────────────── */
  {
    id: "5",
    title: "Tráfico de Drogas",
    description: "Normalização de nomes de réus e substâncias em autos de apreensão.",
    aiContext: "",
    tasks: { normalize: true, classify: false },
    columnsToNormalize: ["réu", "substância"],
    columnsToClassify: [],
    normalizations: 870,
    classifications: 0,
    lastRun: null,
    createdAt: "2026-05-17T00:00:00Z",
    uploadedFile: {
      id: "f5",
      name: "tráfico_2025.csv",
      size: 34000,
      rows: 1870,
      uploadedAt: "2026-05-19T08:00:00Z",
    },
    normalizedFile: null,
  },
  {
    id: "6",
    title: "Fraudes Tributárias",
    description: "Classificação de tipos de fraude e normalização de CNPJs envolvidos.",
    aiContext: "Considerar nomenclatura da Receita Federal.",
    tasks: { normalize: true, classify: true },
    columnsToNormalize: ["empresa", "cnpj"],
    columnsToClassify: ["tipo_fraude"],
    normalizations: 412,
    classifications: 890,
    lastRun: null,
    createdAt: "2026-05-15T00:00:00Z",
    uploadedFile: {
      id: "f6",
      name: "fraudes_fiscais_q1.xlsx",
      size: 56000,
      rows: 2900,
      uploadedAt: "2026-05-19T09:30:00Z",
    },
    normalizedFile: null,
  },

  /* ── Requer ação ──────────────────────────────── */
  {
    id: "7",
    title: "Homicídios Dolosos",
    description: "Normalização de autores e vítimas em boletins de homicídio doloso.",
    aiContext: "",
    tasks: { normalize: true, classify: false },
    columnsToNormalize: ["autor", "vítima"],
    columnsToClassify: [],
    normalizations: 1640,
    classifications: 0,
    lastRun: "2026-05-14T11:00:00Z",
    createdAt: "2026-04-20T00:00:00Z",
    uploadedFile: {
      id: "f7",
      name: "homicidios_2025.csv",
      size: 41000,
      rows: 3100,
      uploadedAt: "2026-05-14T10:00:00Z",
    },
    normalizedFile: null,
    hasError: true,
  },
  {
    id: "8",
    title: "Lavagem de Dinheiro",
    description: "Extração de envolvidos e valores em processos de lavagem de ativos.",
    aiContext: "Priorizar entidades financeiras e operadores citados.",
    tasks: { normalize: true, classify: true },
    columnsToNormalize: ["envolvido", "instituição"],
    columnsToClassify: ["papel"],
    normalizations: 2205,
    classifications: 3140,
    lastRun: "2026-05-12T16:45:00Z",
    createdAt: "2026-04-10T00:00:00Z",
    uploadedFile: {
      id: "f8",
      name: "lavagem_ativos_2025.xlsx",
      size: 93000,
      rows: 5400,
      uploadedAt: "2026-05-12T15:00:00Z",
    },
    normalizedFile: null,
    hasError: true,
  },
];
