"""add_dictionary_entries_table

Revision ID: 4ec107f5c802
Revises: 7e6f0580b03a
Create Date: 2026-05-13 11:54:01.392605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4ec107f5c802'
down_revision: Union[str, None] = '7e6f0580b03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dictionary_project', 'dictionary_entries', ['project_id'], unique=False, postgresql_where=sa.text('project_id IS NOT NULL'))
    op.create_index('idx_dictionary_user', 'dictionary_entries', ['user_id'], unique=False)
    op.create_index('uq_dictionary_global', 'dictionary_entries', ['user_id', 'kind', 'name'], unique=True, postgresql_where=sa.text('project_id IS NULL'))
    op.create_index('uq_dictionary_project', 'dictionary_entries', ['project_id', 'kind', 'name'], unique=True, postgresql_where=sa.text('project_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_dictionary_project', table_name='dictionary_entries', postgresql_where=sa.text('project_id IS NOT NULL'))
    op.drop_index('uq_dictionary_global', table_name='dictionary_entries', postgresql_where=sa.text('project_id IS NULL'))
    op.drop_index('idx_dictionary_user', table_name='dictionary_entries')
    op.drop_index('idx_dictionary_project', table_name='dictionary_entries', postgresql_where=sa.text('project_id IS NOT NULL'))
    op.drop_table('dictionary_entries')
    # ### end Alembic commands ###
