"""add_users_auth_and_projects_tables

Revision ID: 7e6f0580b03a
Revises: 4ab000c8f736
Create Date: 2026-05-11 18:46:18.872430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e6f0580b03a'
down_revision: Union[str, None] = '4ab000c8f736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
