"""

Revision ID: b7419e8b9755
Revises: a1b2c3d4e5f6
Create Date: 2026-05-28 00:38:38.533867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7419e8b9755'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_dict_app_entry'), table_name='dictionary_applications')
    op.drop_index(op.f('idx_dict_app_project'), table_name='dictionary_applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_dict_app_project'), 'dictionary_applications', ['project_id'], unique=False)
    op.create_index(op.f('idx_dict_app_entry'), 'dictionary_applications', ['entry_id'], unique=False)
    # ### end Alembic commands ###
