"""create activities table

Revision ID: c89ed0b4ddd0
Revises: b7419e8b9755
Create Date: 2026-06-02 14:14:56.561975

Changes:
- Create activities table with columns: id, user_id, project_id, type, project_name, created_at
- Add foreign key user_id → users.id (CASCADE DELETE)
- Add foreign key project_id → projects.id (CASCADE DELETE)
- Add index idx_activities_user_created on (user_id, created_at) for pagination queries
- Add index idx_activities_project_id on (project_id) for project-scoped lookups

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c89ed0b4ddd0'
down_revision: Union[str, None] = 'b7419e8b9755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_project_id', 'activities', ['project_id'], unique=False)
    op.create_index('idx_activities_user_created', 'activities', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activities_user_created', table_name='activities')
    op.drop_index('idx_activities_project_id', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
